image: docker:git
services:
  - docker:dind

stages:
  - build
#  - publish

before_script:
  - export CI_BUILD_DATE=$(date -u +%Y%m%d-%H%M%S)
  - export CI_DOCKER_IMAGE_VERSION=$CI_BUILD_DATE.${CI_COMMIT_SHA:0:8}

build:
  image: docker pull python
  stage: build
  artifacts:
    paths:
      - dist/*
  script:
    - python Find_schema/Schema_extraction_Script.py